### ISSUE TITLE
Cannot ssh to user container: OCI runtime exec failed error

### ISSUE THREAD

**Issue by floion** [balena-os/balena-up-board#112]
When trying to ssh to a user container it fails with:

> Spawning shell... OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "read init-p: connection reset by peer": unknown OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "read init-p: connection reset by peer": unknown SSH session disconnected

**Comment by dremsol** [comment]
We ran against the same issue

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-up-board/pull/111

**Comment by dremsol** [comment]
When will the latest release be available in BalenaCloud which fixes this issue?

**Comment by floion** [comment]
Hi, sorry for the delay. It should happen in the following day or two

**Comment by dremsol** [comment]
@floion, some days have past and I'm in high need of this release. Can you make it available for update?

**Comment by floion** [comment]
Hi. Sorry for the delay. We'll work to put it on top of our priority queue.

**Comment by DomenicP** [comment]
Any update on this? My team is also running into the same issue.

**Comment by dremsol** [comment]
@floion, I'm well aware of the delays with host extensions related to jetson family of devices. However, I do need a solution for this issue as we are 2 months down the line again. We do have devices in production which we can simply cannot reach in order to backup our data. Can you give us a resolution?

**Comment by floion** [comment]
Hi all, I know I must sound like a broken record by now but I aim for a release early next week.
Stay tuned and sorry for the hassle.

**Comment by floion** [comment]
This would be finally fixed by https://github.com/balena-os/balena-up-board/pull/116
Will aim to get it to production Monday or Tuesday the latest

**Comment by dremsol** [comment]
Hi @floion , thanks for getting #116 trough. I've flashed a device in staging a couple of days ago and can confirm my applications runs again. I would like to update my device in the field today, could you release it to production?

**Comment by floion** [comment]
Hi. Currently investigating a reboot problem on the Up Squared so can't release just yet. Keep you in the loop

**Comment by floion** [comment]
Hi all. We have released OS version `v2.68.1+rev1` which should solve this issue.
Sorry it took so long, various issues popped making this take longer than expected.
