### ISSUE TITLE
Enable I/O accounting in kernel configuration

### ISSUE THREAD

**Issue by mtoman** [balena-os/balena-up-board#114]
This is necessary to use I/O monitoring tools such as `iotop`. This concerns the following options: `CONFIG_TASKSTATS`, `CONFIG_TASK_DELAY_ACCT` and `CONFIG_TASK_IO_ACCOUNTING`.

**Comment by alexgg** [comment]
We should probably add these by default for all device types.

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/meta-balena/issues/2066
