### ISSUE TITLE
create release with Supervisor >= v12.8.0 and NM >= 1.32

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-up-board#130]
A customer needs builds with Supervisor 12.8.0 or greater which contain the ability to disable device metrics to reduce bandwidth.

This Supervisor version was available up-stream in meta-balena since [v2.80.5](https://github.com/balena-os/meta-balena/blob/master/CHANGELOG.md#v2805)

**Comment by cywang117** [comment]
Current latest is `v2.89.15` as of writing this, which comes with Supervisor v12.11.16 and NM 1.32.12.
