### ISSUE TITLE
Up-core doesn't get back online after reboot

### ISSUE THREAD

**Issue by horia-delicoti** [balena-os/balena-up-board#70]
device: `up-core`
balenaos: `2.32.0+rev1`
supervisor: `9.14.0`

Steps to reproduce the issue:
1) Provision a device online
2) Reboot a couple of times
3) On a `dev` image, you should see on the monitor:
```
dmesg
brcmf_cfg80211_reg_notifier: not a ISO30166 code (0x30 0x30)
```

**Comment by floion** [comment]
This does not reproduce on v2.68.1+rev1
