### ISSUE TITLE
User wants to have SPI enabled

### ISSUE THREAD

**Issue by imrehg** [balena-os/balena-up-board#74]
Seems like it was never tested, so should do to see if it's present or not, and what needs for it to be enabled.

**Comment by iAmoric** [comment]
Hi,

What is the status ?

**Comment by floion** [comment]
Hi, it is under work. Will update when the internal discussions on this matter are finished.

**Comment by floion** [comment]
Hi, version `2.54.2+rev1` is now released to production and it contains this functionality
