### ISSUE TITLE
GPIO doesn't work for the user on UP squared

### ISSUE THREAD

**Issue by zrzka** [balena-os/balena-up-board#85]
**balenaOS: 2.29.2+rev1**

User is claiming that the GPIO doesn't work on the UP squared board.

```
cd /sys/class/gpio
echo 478 > export
cd gpio478
echo out > direction
cat direction # returns out
echo 1 > value
cat value # returns 0 :-(
```

Tried other pins (like 432), but still no luck.

> I tried a couple. None of them work. I tried 432 specifically just now with the same result.

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-up-board/pull/109
